### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by edit4ever** [FastEddyCurrent/zap2xml#1]
This script has a great potential, and I'm willing to try to build a kodi addon for it - but first I want to get it running smoothly from the terminal.  I'm getting the following error when executing:

`Exception
error<type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "zap2xml.py", line 1928, in <module>
    main()
  File "zap2xml.py", line 1838, in main
    parseGrid(fn) #data read in and unicode it
  File "zap2xml.py", line 1057, in parseGrid
    p.feed(b)
  File "/usr/lib/python2.7/HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "/usr/lib/python2.7/HTMLParser.py", line 161, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python2.7/HTMLParser.py", line 327, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "zap2xml.py", line 686, in handle_starttag
    globals()['on_%s' % tag](self, tag, attrs)
  File "zap2xml.py", line 441, in on_a
    tnum = tmp.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
`

Any thoughts on what may be causing this?  I'm not that familiar with python, so I'm a bit lost.

**Comment by FastEddyCurrent** [comment]
Looks like it might be a bug. When it's parsing the for the channel numbers the regular expression isn't matching and the return is a none object. This and the Perl script don't really a test suite, so I may need more info like the command line options your using and a lineup id to drive the code. I'm busy for about a week and can't look until then.

**Comment by edit4ever** [comment]
No worries - as an FYI, after running with -a it worked - and from then on it ran with or without the -a.  Strange.  I'll test some more over the next week and let you know if I find anything.

BTW - are you ok if I try to work on a Kodi addon for this?

**Comment by FastEddyCurrent** [comment]
Oops didn't mean to close this. Go ahaed with the addon. The original perl script didn't have a license that I could find. I would credit http://zap2xml.awardspace.info/ for the original and me for the Python port.

**Comment by edit4ever** [comment]
I'm currently testing the kodi add-on elements and am still getting the "NoneType" error when I clear out the cache and start a fresh download.  Not sure what is wrong with that part of the code.  BTW it works fine under TV Guide, but zap2it fails with that error.

In the meantime, if you run kodi and want to test the addon let me know.  I'm travelling, but will update my fork with the files soon...in the meantime I can post the compiled addon for you to download if you want.

**Comment by FastEddyCurrent** [comment]
I put in a fix. It will set channel number to 0 when it's not set rather than throw the exception.

**Comment by edit4ever** [comment]
Thanks that did it!  I've pushed my first set of files for the kodi addon if you're interested in trying.  As I am on the road, I haven't been able to test with Raspberry Pi or OpenELEC/LibreELEC installs of Kodi, but it should work.  FYI - I also have to update license info and icon. I'll close this issue now.  Thanks again!
