### ISSUE TITLE
TV Guide favorites error...

### ISSUE THREAD

**Issue by edit4ever** [FastEddyCurrent/zap2xml#2]
The test as a kodi addon has been going well!  I'm now testing different options for the addon and it seems I've hit an error in using TV Guide as a source with favorites.  perhaps something similar to the issue we had with the zap2it favorites?  Here's the output from running the script (I've replaced the login info):

```
# python zap2xml.py -u XXXXXXXX -p XXXXXXXXXX -d 1 -z
Reading config file: /storage/.kodi/addons/tools.module.zap2xml/.zap2xmlrc

zap2xml.py:589: UserWarning: gzip transfer encoding is experimental!
  br.set_handle_gzip(True)
Logging in as XXXXXXXXXXXXXXX

Getting: http://www.tvguide.com/signin/
Cookie:
<Cookie Provider=Broadcast for .tvguide.com/>:Function: loginTVG :Line: 1561
Cookie:
<Cookie ProviderFullName=San+Diego+Area+Broadcast+%28San+Diego%29 for .tvguide.com/>:Function: loginTVG :Line: 1561
Cookie:
<Cookie ProviderOffset=-25200 for .tvguide.com/>:Function: loginTVG :Line: 1561
Cookie:
<Cookie ProviderOffsetNext=-28800 for .tvguide.com/>:Function: loginTVG :Line: 1561
Cookie:
<Cookie ProviderOffsetNextStart=1478422800 for .tvguide.com/>:Function: loginTVG :Line: 1561
Cookie:
<Cookie ProviderPrimetime=20 for .tvguide.com/>:Function: loginTVG :Line: 1561
Cookie:
<Cookie ProviderPrimetimeNext=20 for .tvguide.com/>:Function: loginTVG :Line: 1561
Cookie:
<Cookie ServiceID=20551 for .tvguide.com/>:Function: loginTVG :Line: 1561
Getting: http://www.tvguide.com/user/favorites/?provider=20551
Lineup 20551 favorites: [u'15.1', u'15.2', u'33.1', u'33.2', u'69.1', u'69.3', u'69.2', u'12.1', u'49.1', u'27.2', u'27.1', u'17.1', u'6.2', u'6.1', u'57.1', u'49.2', u'39.2', u'45.1', u'39.1']
Getting: http://mobilelistings.tvguide.com/Listingsweb/ws/rest/schedules/20551/start/1465390800/duration/180
[1/8] Parsing:/storage/.kodi/addons/tools.module.zap2xml/cache/1465390800000.js.gz
Exception
error<type 'exceptions.KeyError'>
Traceback (most recent call last):
  File "zap2xml.py", line 1931, in <module>
    main()
  File "zap2xml.py", line 1797, in main
    parseTVGGrid(fn)
  File "zap2xml.py", line 950, in parseTVGGrid
    if cs != tvgfavs[n]:
KeyError: u'3.1'

```

The channel 3.1 that it errors on is in the full lineup, but not in my favorites. If I run this with all channels it works great.  Not sure if you have any thoughts on this. Thanks!

**Comment by FastEddyCurrent** [comment]
Try the latest change. It was a bug to go looking for a channel in favorites that wasn't there..I could only reproduce this once on the site. A new channel was added that I didn't originally have.  Now it skips over the non-favorite channels like it supposed to.

**Comment by edit4ever** [comment]
That worked - thanks!  Interestingly, I can't seem to get Tvheadend to read the xmltv file when outputting data from TVguide.  Works fine when using data from zap2it.  As far as I can tell, there doesn't seem to be a difference in the files (except for some of the content that TVguide includes)... it's the weirdest thing... but I'll keep hunting.  In the meantime - the favorites issue is resolved!
