### ISSUE TITLE
error with program details or icons...

### ISSUE THREAD

**Issue by edit4ever** [FastEddyCurrent/zap2xml#4]
OK new error when adding the -D or -I option when using TVguide as source:

```
Parsing:/storage/.kodi/addons/tools.module.zap2xml/cache/1465520400000.js.gz
Exception
error<type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/storage/.kodi/addons/tools.module.zap2xml/zap2xml.py", line 1931, in <module>
    main()
  File "/storage/.kodi/addons/tools.module.zap2xml/zap2xml.py", line 1797, in main
    parseTVGGrid(fn)
  File "/storage/.kodi/addons/tools.module.zap2xml/zap2xml.py", line 1045, in parseTVGGrid
    fn = os.path.join(cacheDir, cp + ".js.gz")
TypeError: unsupported operand type(s) for +: 'int' and 'str'

```

I'm probably pushing this further than you have time for - so no worries about responding quickly - you've been extremely helpful so far!  I may just leave out the TVguide option from the addon as the zap2it guide seems to work pretty well.

BTW - I cleared the xmltv file error with the program url by adding </url> to the end of the line. It was originally coded as just />  This is another item that only shows up when using TVguide as source, and I'm not sure why that gets in the xmltv file as I don't believe it has any purpose for the epg.  It's just a link to the details of the program on tvguide.

**Comment by edit4ever** [comment]
I've also noticed that using the -D is not actually pulling the extra details into the xmltv file.  It is downloading the extra data and saving the episode .js.gz files but doesn't seem to parse them and extract the info (season/episode numbers, longer description, etc) into the xmltv file.

Is this still a set of functions that are being developed or does it work for you?

**Comment by FastEddyCurrent** [comment]
Big update. I found about 5 bugs for tv guide (which I don't use but ported). One big one for tv guide that wasn't creating the file for image icons or details. The detailed description wasn't set properly. Thiese were mostly porting errors from the original.

**Comment by edit4ever** [comment]
-D, -I and -i are working great for zap2it...doesn't seem like they're working for TVguide. I'm getting the same description data and no channel icons.  Also, on the second running of the script, TVguide downloads all stations, not just favorites, and is outputting them to the xmltv file.  Strange as it runs fine in the first pass.

For the zap2it pull of extra details...when you are on the wesbite, you can see the common season episode numbers - it doesn't look like that is being parsed, only the dd_progid version of the episode number.  Not sure if the common numbers is something that could be parsed?

**Comment by FastEddyCurrent** [comment]
TV guide and Zap2it will have different XML file data for the sites.
The original perl script was written for Zap2it and TV Guide seems like it was added later.
The original perl script for Zap2it  doesn't get common numbers, If I get time I'll look to see if it can be done.
-D for TV Guide only tries to get release date for movies and an image for the program <icon src=...
-i is not implemented for TV Guide (original perl script), I'll put a warning in.
There's a fix for getting all the channels on an update.

**Comment by edit4ever** [comment]
awesome - thanks for the update and your work on this!  I'll put some notes into the kodi addon about the TVguide limitations.  I'm working to better understand python and the parser - so I'll look through and test as well on the common numbers.

**Comment by FastEddyCurrent** [comment]
Well, there's a lot more detailed data for Zap. including season and episode yet to come.

**Comment by edit4ever** [comment]
You're right - I think the TVguide stuff should be left out.  BTW, I was just testing and it seems that while -D for Zap is pulling the extended info for an episode and creating the .js.gz cache files...the information is not being written into the xmltv file.  There is data for genre, common season and episode numbers, original air date and an extended program decription.  It's all in the file, but it's just not being written out.  It seems like the system is parsing the data but not writing it out.  Any thoughts on this?

**Comment by FastEddyCurrent** [comment]
yep

**Comment by edit4ever** [comment]
Thanks for your fixes...I caught a couple of issues with season/episode numbers and have updated.

I'm working on two other issues...first, with -I the program icons work fine on the first run of the grab - but the next time the script runs, the program icon url is not output to the xmltv file.

The second issue is figuring out how to deal with the extended program description information.  When you run the -D you get a longer program description, but it seems that because the short program description already exists, nothing is done with the extra information.  I don't think two descriptions can be output to the xmltv file, it would likely create a lot of duplicate information, but I'm not sure how to make the parser replace the short description with the longer description when -D is enabled.

Thanks again for your earlier fixes and sorry for the misunderstanding of what you meant when you said "yet to come".  :-)

**Comment by edit4ever** [comment]
Found and fixed the issues with the -D and -I options.  I'll close this issue.
